image: python:3.7.3

pipelines:
  default:
    - step:
        script:
          - python setup.py testing
          - coverage run --source=pycha/ setup.py test
          - coverage report
          - flake8 pycha setup.py
